---

# lf-lab-1a:
#     hostname: "172.19.41.223"
#     groups:
#         - arista_group

# lf-lab-1b:
#     hostname: "172.19.41.224"
#     groups:
#         - arista_group

# gss1-lab:
#     hostname: "172.19.40.241"
#     groups:
#         - arista_group

# lab-sp-1:
#     hostname: "172.19.41.133"
#     groups:
#         - arista_group

# LONDON

lf-cl-1a-oob:
    hostname: "lf-cl-1a-oob"
    groups:
        - arista_group_live

lf-cl-1b-oob:
    hostname: "lf-cl-1b-oob"
    groups:
        - arista_group_live

lf-cl-2a-oob:
    hostname: "lf-cl-2a-oob"
    groups:
        - arista_group_live

lf-cl-2b-oob:
    hostname: "lf-cl-2b-oob"
    groups:
        - arista_group_live

lf-cl-3a-oob:
    hostname: "lf-cl-3a-oob"
    groups:
        - arista_group_live

lf-cl-3b-oob:
    hostname: "lf-cl-3b-oob"
    groups:
        - arista_group_live

lf-cl-4a-oob:
    hostname: "lf-cl-4a-oob"
    groups:
        - arista_group_live

lf-cl-4b-oob:
    hostname: "lf-cl-4b-oob"
    groups:
        - arista_group_live

lf-cl-5a-oob:
    hostname: "lf-cl-5a-oob"
    groups:
        - arista_group_live

lf-cl-5b-oob:
    hostname: "lf-cl-5b-oob"
    groups:
        - arista_group_live

lf-cl-6a-oob:
    hostname: "10.108.204.61"
    groups:
        - arista_group_live

lf-cl-6b-oob:
    hostname: "10.108.204.62"
    groups:
        - arista_group_live

lf-gss-1a-oob:
    hostname: "lf-gss-1a-oob"
    groups:
        - arista_group_live

lf-gss-1b-oob:
    hostname: "lf-gss-1b-oob"
    groups:
        - arista_group_live

lf-gss-2a-oob:
    hostname: "lf-gss-2a-oob"
    groups:
        - arista_group_live

lf-gss-2b-oob:
    hostname: "lf-gss-2b-oob"
    groups:
        - arista_group_live

lf-gss-3a-oob:
    hostname: "lf-gss-3a-oob"
    groups:
        - arista_group_live

lf-gss-3b-oob:
    hostname: "lf-gss-3b-oob"
    groups:
        - arista_group_live
